### ISSUE TITLE
CodeSandbox Deployment

### ISSUE THREAD

**Issue by SaraVieira** [codaxy/cxjs-codesandbox-template#1]
Hey! 👋

I am working on the netlify integration for codesandbox and the template needs some changes to be able to work with that :(

We need a build script, is there a way you can add that?

Also since you are using SASS probably SASS loader and node-sass

Is this okay ?

**Comment by mstijak** [comment]
Sure, I'll add that.

**Comment by mstijak** [comment]
I have added dev dependencies and build scripts in #2. Does that work for you?
